networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      -"80:80"
    volumes:
      -'./nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      -backend
      -frontend
  backend:
    build:
      context: ./FixIT
    networks:
      - dev


  frontend:
    build:
      context: ./LoginPageReactExample-main
    networks:
      - dev
